In [1]:
import sys
import pandas as pd
import tools
import logging

sys.path.append('../database')  # Add the 'database' directory to the Python path
sys.path.append('../../')   
from db_connections import get_database_connection

Engine(postgresql://postgres:***@localhost:5432/financas)

In [6]:
class Credit_Card_Statement_Pipeline:
    """Credit_Card_Statement_Pipeline: de ingestão de dados
     Attributes
    ----------
    type: str
        Define what type of extraction. Options: csv
    origin_path: str
        address of the extraction data
    load_path: str
        Address of the load table

    Methods
    extract():
        Extracts the information
    tranform()
    load()
    """



    def __init__(self) -> None:
        self.df=None
        self.cliente_id=None
        self.conta_id=None
        self.load_path=None
    def extract(self,origin_path):

        self.file_type=tools.get_file_type(origin_path)
        if self.file_type=='csv':
            self.df = pd.read_csv(origin_path)
        elif self.file_type in ('xls','xlsx'):
            self.df = pd.read_excel(origin_path)
        
        file_name=tools.get_fileName_from_filePath(origin_path)
        self.cliente_id=tools.get_userId_from_fileName(file_name)
        self.conta_id=tools.get_accountId_from_fileName(file_name)
        

    def transform(self):

        #Limpando linhas de saldo
        self.df = self.df[self.df['lançamento'] != "Controle de saldo"]

        #Renomeando as colunas
        self.df.rename(columns={'lançamento':'ref_fonte'},inplace=True)


        self.df['tipo_transacao']='cartão de crédito'
        self.df['conta_id']=self.conta_id
        self.df['usuario_id']=self.cliente_id

    def load(self,load_path='fato.transacao'):
        engine,connection=get_database_connection(existDB=True,engine='sqlAlchemy')
        n=self.df.to_sql(load_path, connection, if_exists='append', index=False)
        connection.commit()
        connection.close()
        tools.load_legado(self.df,'fatura')

In [7]:
origin_path='files\\extratos\\1_1_fatura_202512.csv'
pipeline=Credit_Card_Statement_Pipeline()
log = logging.getLogger(__name__)
log.info('Extraindo Dados')
pipeline.extract(origin_path)
pipeline.df.head(100)

          data                                lançamento    valor
0   2025-12-15                         Controle de saldo     0.00
1   2025-12-10  PANVEL MATRIZ          ELDORADO DO S BRA   313.56
2   2025-12-08  Amazon Digital BR      SAO PAULO     BRA    35.91
3   2025-12-07                   SHOPEE *LAJVARIEDA01/02   196.93
4   2025-12-06  Amazon Digital BR      SAO PAULO     BRA    28.54
5   2025-12-06  PG *RAIZS ORGANICOS LT SAO PAULO     BRA    69.40
6   2025-12-04  ENTRE PATAS E PELOS    SAO PAULO     BRA   410.70
7   2025-12-04  MERCADOLIVRE*MERCADOL  SAO PAULO     BRA    19.01
8   2025-12-03  MERCADOLIVRE*MERCADOL  So Paulo      BRA    31.99
9   2025-12-02  SHOPEE *LaTuttyBabySto Novo Hamburgo BRA   135.84
10  2025-12-02  MIDAS ARTIGOS PARA PRE SAO PAULO     BRA   139.97
11  2025-12-01                   Shopee*SHOPEE*NewD01/02    85.27
12  2025-11-30  INSTITUTO CU-CT AL ALE BELO HORIZONT BRA    40.00
13  2025-11-30  JUJUBA EDITO-CT        SAO PAULO     BRA    34.00
14  2025-11-30  OZE         -CT        SAO PAULO     BRA    42.50
15  2025-11-29  ConectC*JessicaMac     SAO PAULO     BRA    50.00
16  2025-11-26  FAR PARK EST-CT NAMENT SAO PAULO     BRA    30.00
17  2025-11-26  PANVEL MATRIZ          ELDORADO DO S BRA   128.90
18  2025-11-26  SHOPEE *SHPSTECNOLOGIA SAO PAULO     BRA    29.90
19  2025-11-25  MERCADOLIVRE*2PRODUTO  So Paulo      BRA    68.30
20  2025-11-24  PANVEL MATRIZ          ELDORADO DO S BRA   183.79
21  2025-11-23  ConectC*JessicaMac     SAO PAULO     BRA    50.00
22  2025-11-22  PG *RAIZS ORGANICOS LT SAO PAULO     BRA    69.40
23  2025-11-20  ConectC*JessicaMac     SAO PAULO     BRA    50.00
24  2025-11-19                        PAGAMENTO EFETUADO -3859.48
25  2025-11-16  Estacionamento 1QYXCX  Sao Paulo     BRA    34.20
26  2025-11-15  Amazon Digital BR      SAO PAULO     BRA    34.23
27  2025-11-15  CORA BAR E R-CT URANT  SAO PAULO     BRA   438.44
28  2025-11-13  PETZ DIGITAL           EMBU          BRA   170.96
29  2025-11-11  Shopee*SHOPEE*Hdql02/02Cotia         BRA   196.84
30  2025-11-11  Shopee*SHOPEE*Hdqlar   Cotia         BRA    -0.01
31  2025-11-09  HOTEL NACIONAL ADM02/05RIO DE JANEIR BRA   691.59
32  2025-11-09  HOTEL NACIONAL ADMINIS RIO DE JANEIR BRA    -0.16
33  2025-10-08  BURITI COMER-CT   03/03SAO PAULO     BRA   153.30
34  2025-10-01  RENNER            03/03CABREUVA      BRA   116.48
35  2025-09-24  MERCADOLIVRE*MERCA03/03PERUIBE       BRA    22.99
36  2025-08-19  PORTO SEGURO CIA S04/10SAO PAULO     BRA   231.14

In [8]:
log.info('Transformando Dados')
pipeline.transform()
pipeline.df

,data,ref_fonte,valor,tipo_transacao,conta_id,usuario_id
1,2025-12-10,PANVEL MATRIZ ELDORADO DO S BRA,313.56,cartão de crédito,1,1
2,2025-12-08,Amazon Digital BR SAO PAULO BRA,35.91,cartão de crédito,1,1
3,2025-12-07,SHOPEE *LAJVARIEDA01/02,196.93,cartão de crédito,1,1
4,2025-12-06,Amazon Digital BR SAO PAULO BRA,28.54,cartão de crédito,1,1
5,2025-12-06,PG *RAIZS ORGANICOS LT SAO PAULO BRA,69.40,cartão de crédito,1,1
6,2025-12-04,ENTRE PATAS E PELOS SAO PAULO BRA,410.70,cartão de crédito,1,1
7,2025-12-04,MERCADOLIVRE*MERCADOL SAO PAULO BRA,19.01,cartão de crédito,1,1
8,2025-12-03,MERCADOLIVRE*MERCADOL So Paulo BRA,31.99,cartão de crédito,1,1
9,2025-12-02,SHOPEE *LaTuttyBabySto Novo Hamburgo BRA,135.84,cartão de crédito,1,1
10,2025-12-02,MIDAS ARTIGOS PARA PRE SAO PAULO BRA,139.97,cartão de crédito,1,1
11,2025-12-01,Shopee*SHOPEE*NewD01/02,85.27,cartão de crédito,1,1
12,2025-11-30,INSTITUTO CU-CT AL ALE BELO HORIZONT BRA,40.00,cartão de crédito,1,1
13,2025-11-30,JUJUBA EDITO-CT SAO PAULO BRA,34.00,cartão de crédito,1,1
14,2025-11-30,OZE -CT SAO PAULO BRA,42.50,cartão de crédito,1,1
15,2025-11-29,ConectC*JessicaMac SAO PAULO BRA,50.00,cartão de crédito,1,1
16,2025-11-26,FAR PARK EST-CT NAMENT SAO PAULO BRA,30.00,cartão de crédito,1,1
17,2025-11-26,PANVEL MATRIZ ELDORADO DO S BRA,128.90,cartão de crédito,1,1
18,2025-11-26,SHOPEE *SHPSTECNOLOGIA SAO PAULO BRA,29.90,cartão de crédito,1,1
19,2025-11-25,MERCADOLIVRE*2PRODUTO So Paulo BRA,68.30,cartão de crédito,1,1
20,2025-11-24,PANVEL MATRIZ ELDORADO DO S BRA,183.79,cartão de crédito,1,1
21,2025-11-23,ConectC*JessicaMac SAO PAULO BRA,50.00,cartão de crédito,1,1
22,2025-11-22,PG *RAIZS ORGANICOS LT SAO PAULO BRA,69.40,cartão de crédito,1,1
23,2025-11-20,ConectC*JessicaMac SAO PAULO BRA,50.00,cartão de crédito,1,1
24,2025-11-19,PAGAMENTO EFETUADO,-3859.48,cartão de crédito,1,1
25,2025-11-16,Estacionamento 1QYXCX Sao Paulo BRA,34.20,cartão de crédito,1,1
26,2025-11-15,Amazon Digital BR SAO PAULO BRA,34.23,cartão de crédito,1,1
27,2025-11-15,CORA BAR E R-CT URANT SAO PAULO BRA,438.44,cartão de crédito,1,1
28,2025-11-13,PETZ DIGITAL EMBU BRA,170.96,cartão de crédito,1,1
29,2025-11-11,Shopee*SHOPEE*Hdql02/02Cotia BRA,196.84,cartão de crédito,1,1
30,2025-11-11,Shopee*SHOPEE*Hdqlar Cotia BRA,-0.01,cartão de crédito,1,1
31,2025-11-09,HOTEL NACIONAL ADM02/05RIO DE JANEIR BRA,691.59,cartão de crédito,1,1
32,2025-11-09,HOTEL NACIONAL ADMINIS RIO DE JANEIR BRA,-0.16,cartão de crédito,1,1
33,2025-10-08,BURITI COMER-CT 03/03SAO PAULO BRA,153.30,cartão de crédito,1,1
34,2025-10-01,RENNER 03/03CABREUVA BRA,116.48,cartão de crédito,1,1
35,2025-09-24,MERCADOLIVRE*MERCA03/03PERUIBE BRA,22.99,cartão de crédito,1,1
36,2025-08-19,PORTO SEGURO CIA S04/10SAO PAULO BRA,231.14,cartão de crédito,1,1

In [9]:
log.info('Carregando Dados')
pipeline.load('financas.fato.transacao')

KeyError: 'ref_original'